services:
  postgres:
    image: pgvector/pgvector:pg16
    container_name: nexus-postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
      POSTGRES_DB: mydb
    ports:
      - '5432:5432'
    volumes:
      - nexus-postgres:/var/lib/postgresql/data
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U nexus -d nexus']
      interval: 5s
      timeout: 5s
      retries: 10

  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: nexus-pgadmin
    restart: unless-stopped
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@nexus.com
      PGADMIN_DEFAULT_PASSWORD: nexus
    ports:
      - '5050:80'
    volumes:
      - nexus-pgadmin:/var/lib/pgadmin
    depends_on:
      - postgres

  redis:
    image: redis:7-alpine
    container_name: nexus-redis
    restart: unless-stopped
    ports:
      - '6379:6379'
    volumes:
      - nexus-redis:/data
    command: redis-server --appendonly yes

  redisinsight:
    image: redis/redisinsight:latest
    ports:
      - '5540:5540'
    volumes:
      - nexus-redisinsight:/data
    depends_on:
      - redis

volumes:
  nexus-postgres:
  nexus-redis:
  nexus-redisinsight:
  nexus-pgadmin:
